# Usa una imagen oficial de Node.js
FROM node:16

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Construir la aplicación de React
RUN npm run build

# Usa un servidor web ligero como nginx para servir la aplicación
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Expone el puerto en el que corre el frontend
EXPOSE 80

# No necesitas CMD, Nginx ya lo tiene por defecto
