version: '2'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/tu_base_de_datos  # Agrega esta línea para la conexión a MongoDB
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
