# Using a smaller base image
FROM node:alpine AS build

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Build the application
RUN npm run build

# Production container
FROM node:alpine AS production
WORKDIR /app

# Copy build and node_modules from the previous stage
COPY --from=build /app .

# Expose the port and define CMD
EXPOSE 3000
CMD ["npm", "start"]
